### ISSUE TITLE
Hall county webscraper

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#11]
Make webscraper that spits out a CSV.

Please make a subfolder under src/webscraper that is the county name and contains all your code (Python 3.6) so no merge conflicts.

http://www.hallcounty.org/741/Inmate-Population-List
Current roster there, but no race information, and no release dates. I emailed them to ask about how to get both.

**Comment by JogoShugh** [comment]
I'll grab this

**Comment by lahoffm** [comment]
Please also add a README.md explaining how to install/run it and basic output to expect.

**Comment by lahoffm** [comment]
CSV output format?
https://github.com/lahoffm/aclu-bail-reform/blob/master/CONTRIBUTING.md

**Comment by lahoffm** [comment]
My email to sheriff: "Your website does not provide the race of inmates or release dates for past inmates, is there any way I could obtain this information? Also, is the list of current inmates the "pre-trial" inmates or also those sentenced?"

Sheriff's response: "The website is the only location where public access may be obtained."

**Comment by lahoffm** [comment]
@JogoShugh  are you still working on this? If you don't have time to devote to this over next few weeks please let me know so I can open it up for others.
