### ISSUE TITLE
Henry county webscraper

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#12]
Make webscraper that spits out a CSV.

Please make a subfolder under src/webscraper that is the county name and contains all your code (Python 3.6) so no merge conflicts.

http://www.henrycountysheriff.net/InmateInformation
Race and charge yes, but no release dates. Click on the "Search inmates" to view all inmates, without entering anything in the text boxes.

**Comment by lahoffm** [comment]
Please also add a README.md explaining how to install/run it and basic output to expect.

**Comment by EnduringBeta** [comment]
I'm on this tonight!

**Comment by lahoffm** [comment]
**Henry county is now open again for anyone to grab.**

 @EnduringBeta made a folder, copied the Athens-Clarke scraper and made some small changes to get us started. But **most of the code has to be deleted/changed** because it's still specific to Athens-Clarke. Feel free to do so.

**Comment by ksheffield3** [comment]
Jumping on this webscraper!
