### ISSUE TITLE
Lowndes county webscraper

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#13]
Make webscraper that spits out a CSV.

Please make a subfolder under src/webscraper that is the county name and contains all your code (Python 3.6) so no merge conflicts.

http://www.lowndessheriff.com/default.asp?P=current_inmates 
Current roster with race and charge: yes.  But only county that does NOT have the arrest date (and also doesn’t say if they are in jail pre-trial or not).
Release dates: no but maybe could infer this from looking at when people disappear from roster (but that could mean they are sentenced and not released).

**Comment by MotorizedWandOfFury** [comment]
I'll take this one

**Comment by MotorizedWandOfFury** [comment]
So it looks like the page has `<meta content="NOINDEX, NOFOLLOW" name="ROBOTS"/>`.
So as a good internet citizen, I don't believe we can scrap this one. @lahoffm

**Comment by lahoffm** [comment]
Isn't that tag just for search engines not to index this? One possible reason for this is so people won't google someone's name and they show up as an inmate who hasn't even been convicted of a crime yet. What we're doing is the same as if we manually clicked and got that information. So I would guess it's still OK to get the info.

I sent them an email to ask about this.

**Comment by lahoffm** [comment]
Please also add a README.md explaining how to install/run it and basic output to expect.

**Comment by lahoffm** [comment]
CSV output format?
https://github.com/lahoffm/aclu-bail-reform/blob/master/CONTRIBUTING.md

**Comment by lahoffm** [comment]
I dispatched ACLU interns to call the jail for us. Remind me if they haven't done it in a couple weeks.

**Comment by lahoffm** [comment]
ACLU intern said "I called the Lowndes County IT department again, and they said that they don't allow for scraping. However, their Director was out of the office, so they couldn't give a finite answer. I have given them my contact information and am awaiting a response from the Director. The IT department's number: 229.671.2450"
