### ISSUE TITLE
Richmond county webscraper

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#15]
Make webscraper that spits out a CSV.

Please make a subfolder under src/webscraper that is the county name and contains all your code (Python 3.6) so no merge conflicts.

http://appweb2.augustaga.gov/InmateInquiry/AltInmatesOnline.aspx
Plain HTML data probably has current roster (but I’m confused about what “sentenced/released/blank” means). Includes race and charge but not release date. They say “sentenced/released” but not when, and there can be multiple charges.

**Comment by lahoffm** [comment]
Please also add a README.md explaining how to install/run it and basic output to expect.

**Comment by MotorizedWandOfFury** [comment]
While we're blocked on Lowndes, I'll take this one.

**Comment by lahoffm** [comment]
@MotorizedWandOfFury are you still working on this? If you don't have time to devote to this over next few weeks please let me know so I can open it up for others.

**Comment by MotorizedWandOfFury** [comment]
Yes, I can still work on this for a couple more weeks.

**Comment by lahoffm** [comment]
Things still to fix if we resume work.

- [ ]	Write a README of what it does (gets the “recent bookings” for richmond) & how to install & run it starting in a clean Python environment, like do you need to do pip selenium? (runs under selenium 3.6.0, python 3.6.3 in my system)
- [ ]	Inmate names are sometimes parsed incorrectly. Try making a CSV & see what I mean.
- [ ]	Many inmates in “recent bookings” aren’t saved to the CSV. For example there should have been 37 names based on the website but there were only 23 saved when I ran it. Strangely sometimes it does save all the names and sometimes it doesn’t. Maybe a clue is when it gets all the names it says ‘Dom updated, trying to get all link IDs again’ but when it doesn’t, that print statement isn’t there.
- [x]	Sometimes the charges field is blank, is that a bug or does Richmond legitimately have no charges sometimes
