### ISSUE TITLE
Whitfield county webscraper

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#16]
Make webscraper that spits out a CSV.

Please make a subfolder under src/webscraper that is the county name and contains all your code (Python 3.6) so no merge conflicts.

https://www.whitfieldcountyga.com/p2c/jailinmates.aspx 
Confused about how to tell if someone is a current inmate or not. Data has same format as Columbia county.

**Comment by lahoffm** [comment]
Please also add a README.md explaining how to install/run it and basic output to expect.

**Comment by tonyfast** [comment]
```
import selenium.webdriver
driver = selenium.webdriver.Chrome()
driver.get('https://www.whitfieldcountyga.com/p2c/jailinmates.aspx')
from selenium.webdriver.support.ui import Select
option = driver.find_element_by_css_selector('.ui-pg-selbox option:last-child')
options.click()
body = driver.find_element_by_css_selector('body').text
driver.close()
```

**Comment by lahoffm** [comment]
Moved to #23
