### ISSUE TITLE
Bibb county webscraper

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#2]
Make webscraper that spits out a CSV.

Please make a subfolder under src/webscraper that is the county name and contains all your code (Python 3.6) so no merge conflicts.

http://bibbsheriff.us/isearch/
“View today’s arrests” button (but “no records found”, I wonder when they update it? but no daily inmate roster or release info.

**Comment by kevinglover** [comment]
I can get this

**Comment by lahoffm** [comment]
Please also add a README.md explaining how to install/run it and basic output to expect.

**Comment by lahoffm** [comment]
CSV output format?
https://github.com/lahoffm/aclu-bail-reform/blob/master/CONTRIBUTING.md

**Comment by lahoffm** [comment]
Is the current state of the code enough to close the issue or do you still have some work to do for another pull request?
I'm not going to close the Issue until I've taken a closer look and tried to run the code, probably next week I'll have time.

**Comment by lahoffm** [comment]
One thing you have to do for sure is update the readme to fix the output column names to what the code does now (or just link to my CSV spec page) and rename "dob" field to "inmate_dob".

**Comment by lahoffm** [comment]
A few small things to fix (nb I added one commit to your bibb so pull it down first). This is so we can have the same ETL script process all webscraper. Hopefully, if you fix this that means we're done. I'll close issue when we run it for a week or so & the files all pass unittest #18.

- [x] timestamp, race, booking timestamp, release timestamp, bond_amount are not in format described in CONTRIBUTING.md
- [x] Some spaces showing up as ‘Â’ when I open excel on Windows for booking_timestamp, release_timestamp, charges, bond_amount – text encoding issue probably. Might not be an issue for automated processing but for human readability. In future ACLU might want to look at some CSV files themselves.
- [x] If inmate is listed as “Released” (red text) it doesn’t show up in current_status
- [x] List all charges separated by ' | ' (currently lists just the first charge)

**Comment by kevinglover** [comment]
@lahoffm Looks like Excel doesn’t like UTF-8 encoded files, so that's causing the `Â` when opened in excel. We might have to save CSV files using Windows encoding (Windows-1252). That might be something to add to the CONTRIBUTING.md, since it's not obvious we are dealing with Excel weirdness.

**Comment by lahoffm** [comment]
@kevinglover Do you think you can complete bibb by Monday night including fixing the weird encoding issues? I'm asking because I am hoping to get 4 scrapers running daily by Nov 1 and you'd be one of those. If you don't think you'll have time, I might try to finish the remaining issues myself.

**Comment by lahoffm** [comment]
I finished the bibb scraper, barring any bugs that pop up during data collection. Will close issue once unittests written & it passes unittests for a few days.

Thank you so much @kevinglover for your help writing it!
