### ISSUE TITLE
Columbia/Dougherty/Whitfield combo webscraper

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#23]
@imanioliver Replaces #5, #7, #16. All counties show data in similar format using "P2C" system. Can write a single program to get each one. Be sure to account for minor variations between counties especially where in the main page they put the tables. We still want three output CSV files. Webscraper folder should be called 'columbia-dougherty-whitfield'.

**Comment by lahoffm** [comment]
@imanioliver are you still working on this? If you don't have time to devote to this over next couple weeks please let me know, I have another person who might want to work on this too.

**Comment by ssdatar** [comment]
I can get this
