### ISSUE TITLE
Brainstorm what initial analyses we should do

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#28]
What analyses should we do first, and why?

I'd recommend we start with a few low-hanging fruit analyses, that will tell a compelling story.
* easy to write code, given the webscraper CSV outputs (or, whatever Postgres database format we decide from #20)
* results will be useful for ACLU based on project description. Either to help ACLU figure out what's going on in the jails, or to help ACLU lobby state legislators.

Put your suggestions below like
- [ ] bar graph of total misdemeanor & felony bookings in each county in a given month. Would help ACLU target bail reform efforts toward counties with greatest total misdemeanor bookings, because that's where the most people could stand to benefit.

We can make them into separate Issues soon.

**Comment by tactical-foresight** [comment]
-bar graph of days in jail vs severity
-plot of total occurrences of citizen being arrested by days in jail
-video heatmap of arrests where time of video corresponds with time of the day
-heatmaps (with transparency determined by  total occurrences of citizen being arrested) of arreestee's address and their length in jail (can be useful for spotting certain representatives)

**Comment by lahoffm** [comment]
"one piece of data that might help is median income of the arrestee's neighborhood." said Keyvis Damptey.

**Comment by lahoffm** [comment]
From what ACLU has told us so far, most useful types of plots to make short-term would show how long people are staying in jail pre-trial or before they get released (total, misdemeanors & felonies).
