### ISSUE TITLE
Chatham county webscraper

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#3]
Make webscraper that spits out a CSV.

Please make a subfolder under src/webscraper that is the county name and contains all your code (Python 3.6) so no merge conflicts.

http://www.chathamsheriff.org/Corrections/Bookings-24hrs 
http://www.chathamsheriff.org/Corrections/Bookings-72hrs 
Plain HTML data includes race and charge but not release date.
No current inmate roster, just booking info.

**Comment by Joshua-Brent-Collins** [comment]
Going to give this one a shot.

**Comment by lahoffm** [comment]
Please also add a README.md explaining how to install/run it and basic output to expect.

**Comment by lahoffm** [comment]
CSV output format?
https://github.com/lahoffm/aclu-bail-reform/blob/master/CONTRIBUTING.md

**Comment by lahoffm** [comment]
Are you still working on this @Joshua-Brent-Collins ? Luigi said he knows of a group in Savannah GA who might want to write this scraper. If you have it partially done, but no time to finish it, can you submit me a pull request so I can pass it on to Open Savannah group to finish?
