### ISSUE TITLE
Cobb county webscraper

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#4]
Make webscraper that spits out a CSV.

Please make a subfolder under src/webscraper that is the county name and contains all your code (Python 3.6) so no merge conflicts.

http://inmate-search.cobbsheriff.org/enter_name.shtm
Through the “Admissions” link you can get booking data over 3-day intervals (going back to 30 days in the past) that includes, race, charge and release date (but only if they got booked AND also got released during the last 30 days).
They have disclaimer that it’s not necessarily accurate.

**Comment by lahoffm** [comment]
Please also add a README.md explaining how to install/run it and basic output to expect.

**Comment by quantkeyvis** [comment]
I'll take this one

**Comment by rimjieun** [comment]
Submitted PR for minor adjustments.

Made changes in following fields:
- **Bond amount:** changed delimiter _' -'_ to _' - '_
- **Other:** removed charge count from indictment label; fixed duplication bug (`indicted` was printed as `indicted | indicted` and `indicted | indicted` as `indicted | indicted | indicted | indicted`, etc.)
- Swapped **charges** and **severity** fields

Suggestion:
- **Current status:** Scrape bond status (`Paid Bail`, `Open`, etc.) for current status
@quantkeyvis @lahoffm 

Passed data integrity check.

**Comment by lahoffm** [comment]
Suggestion might be good, then we'd know if they were released because they paid bail or because "time served".

**Comment by quantkeyvis** [comment]
Ok on my way home now to work on it

**Comment by lahoffm** [comment]
To fix:

A bug: often it does not have all the charges listed. For example Mr. Boddie Christopher Davis has 2 misdemeanors & 2 felonies but only 2 misdemeanors show up when I make the CSV.
http://inmate-search.cobbsheriff.org/inmDetails.asp?SOID=000776337&BOOKING_ID=19320211770787

Or Montgomery Kate Lauren, she actually has 3 felonies but only two in the CSV.
http://inmate-search.cobbsheriff.org/inmDetails.asp?SOID=001042519&BOOKING_ID=19320355335201

Not everyone has this bug. To reproduce the bug maybe print inmate name & number of charges next to each other and compare with what you see in browser till you find some examples.

More minor things

1.    Your middle name column actually shows first names. Your first name column actually shows middle names (except when there’s just one name then it’s correctly the first name).
a.    Instead of all those if statements & try/catch, might be simpler to split the entire name by spaces, lastname everything before 1st space, firstname everything before 2nd space and middlename everything else whether there’s one or multiple middle names with spaces in between. Or Python has a few name parser libraries you can import.
2.    When you separate your main bond amounts, the ‘, ‘.join statement turns ‘ | ‘ into ‘ , |, ,’ or something weird. So it’s not ‘ | ‘ as we want and there’s extra commas.
3.    Delete the commented-out sections of code that will no longer be used.
4.    Line 183 has wrong indented ‘else’, gave me an error (I fixed but easier if you fix & submit PR)
5.    Can you add a command line argument so we can get various dates in the past instead of just today & last 2 days? For example if we enter “python cobb_scraper.py 30” it would get 30-27 days in past (the maximum allowed by Cobb county), “2” would get day before yesterday, yesterday and today. And please edit the README to let us know about that option.
a.    If this would take too much time let me know and I’ll do it. Technically it’s adding a feature, not fixing a bug. It will be useful to get past bookings to see if people booked 30 days ago were released yet and I would really appreciate ability to do that easily.

**Comment by lahoffm** [comment]
All of those issues are fixed

**Comment by quantkeyvis** [comment]
Hey how's the project been progressing?

**Comment by lahoffm** [comment]
Check our Slack

**Comment by quantkeyvis** [comment]
Will do
