### ISSUE TITLE
De-identify data so we can post it publicly

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#51]
De-identify the names of people in the CSV files, and have a key such that only one or two people have the names. Then we can post the data online for other people to analyze however they want.

One option is a Python script that copies CSV files to a new folder, then replaces identifying information in fields  `inmate_firstname`, `inmate_lastname`, `inmate_middlename`, `inmate_address` with a randomly generated key assigned to each unique value of these. So "John Alex Smith, 100 Anyroad GA" becomes "xoihje dskds sdkfj, weofiu". And someone else with first name "John", in ANY CSV file, would also be "xoihje". And also makes a key-value text file so we can translate it back if necessary. Or we could just make one key for each unique combo of those four fields and substitute it in. Or something like python's `hashlib` library.

Or it could be part of the ETL.

**Comment by luigi** [comment]
To ensure maximum privacy, I suggest a one-way hash (SHA256 should be fine). I don't think it'd be necessary to ever translate the hashes back because the source data would still be available to the project owners.

`import hashlib`
`hashlib.sha256("john smith alex 100 anyroad GA").hexdigest()`
