### ISSUE TITLE
Dekalb county webscraper

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#6]
Make webscraper that spits out a CSV.

Please make a subfolder under src/webscraper that is the county name and contains all your code (Python 3.6) so no merge conflicts.

https://ody.dekalbcountyga.gov/app/JailSearch/#/search
Inmate name search only.

**Comment by rimjieun** [comment]
Will try this one.

**Comment by lahoffm** [comment]
Please also add a README.md explaining how to install/run it and basic output to expect.

**Comment by lahoffm** [comment]
CSV output format?
https://github.com/lahoffm/aclu-bail-reform/blob/master/CONTRIBUTING.md

**Comment by lahoffm** [comment]
I got this email: "In response to your email  about  a jail roster, the DeKalb County Inmate look up on our web page is the only public resource that is available ." Spears, Stacey <SSpears@dekalbcountyga.gov>

**Comment by tonyfast** [comment]
Use the query `a b c d e f g h i j k l m n o p q r s t u v w x y z` to get everything.  Then construct the post request.

**Comment by rimjieun** [comment]
Unfortunately their search engine doesn't allow one-letter queries...so for now I'm just querying 'dkso' to reproduce the post request. I'm not sure if that's getting all the data but I'll play around with the query string some more after I complete formatting some data.

**Comment by rimjieun** [comment]
I am having trouble scraping the Jail View page using Beautiful Soup. For example, when I try to scrape https://ody.dekalbcountyga.gov/app/ViewJailing/#/jailing/1105374, it gives me a different preview page from what I see in the browser (I believe they're using Angular, dunno if that affects anything). I was thinking about giving PyQt4 a shot but haven't gotten to it yet. If you know anything about this, please let me know!

**Comment by lahoffm** [comment]
Don't know about this, we can talk about it tonight if you're coming.

**Comment by rimjieun** [comment]
Dekalb is ready for review. Pull request submitted.
