### ISSUE TITLE
Dougherty county webscraper

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#7]
http://66.110.195.53/p2c_dcso/jailinmates.aspx 
Make webscraper that spits out a CSV.

Please make a subfolder under src/webscraper that is the county name and contains all your code (Python 3.6) so no merge conflicts.

Has race/charge, not sure if has release dates.
It’s the listing that also appeared for a couple other counties.

**Comment by imanioliver** [comment]
I'll work on this one

**Comment by lahoffm** [comment]
Please also add a README.md explaining how to install/run it and basic output to expect.

**Comment by lahoffm** [comment]
Got an email from this county:

"Thank you for your inquiry. It seems that you are actually asking three things. I will respond in reverse order:

Unfortunately, we cannot release information about inmates after they leave our custody. It is at that point that our information about them becomes “criminal history” and can only be released if you have the individual sign a waiver. This would have to be done for each inmate.

The list of inmates available online is a combination of all inmates in custody; to include pretrial, sentenced, City of Albany prisoners, civil contempt prisoners, and others.

Regarding a monthly breakdown, you can submit an open records request monthly for a population report. Such a report would be a snapshot in time and may not address the length of time in jail. Please keep in mind that the length of stay in jail is not necessarily reflective of anything as there are many, many moving parts. For example, a serious crime might not get a bond, therefore the person would remain in jail until trial (which could take quite some time). On the other hand, misdemeanor offenders, upon sentencing, will serve their time in the local jail. Either way, the body stays here for a while. "

**Comment by lahoffm** [comment]
CSV output format?
https://github.com/lahoffm/aclu-bail-reform/blob/master/CONTRIBUTING.md

**Comment by lahoffm** [comment]
Moved to #23
