### ISSUE TITLE
Gwinnett county webscraper

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/aclu-bail-reform#9]
Make webscraper that spits out a CSV.

Please make a subfolder under src/webscraper that is the county name and contains all your code (Python 3.6) so no merge conflicts.

http://www.gwinnettcountysheriff.com/pages/docketbook 
http://www.gwinnettcountysheriff.com/smartwebclient/ 
Docketbook site does not have race info, but smartwebclient does. Smartwebclient also can show release dates.

**Comment by ableonard** [comment]
I'll give this one a shot.

**Comment by lahoffm** [comment]
Please also add a README.md explaining how to install/run it and basic output to expect.

**Comment by lahoffm** [comment]
CSV output format?
https://github.com/lahoffm/aclu-bail-reform/blob/master/CONTRIBUTING.md

**Comment by tonyfast** [comment]
```
from pandas import *
import requests


data = dict(map(lambda x: x.split(':', 1), """alpha:all
dateyear:2017
datemonth:10
status:allrecs
search_submission:Search""".splitlines()))

headers = dict(map(lambda x: map(str.strip, x.split(':', 1)), """Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Content-Length:76
Content-Type:application/x-www-form-urlencoded
Host:www.gwinnettcountysheriff.com
Origin:http://www.gwinnettcountysheriff.com
Referer:http://www.gwinnettcountysheriff.com/pages/DBFiles/DocketBook.php
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36""".splitlines()[:-1]))

response=requests.request('POST', "http://www.gwinnettcountysheriff.com/pages/DBFiles/results.php", headers=headers, data=data)
results = read_html(response.text)[0]

single=requests.request('POST', "http://www.gwinnettcountysheriff.com/pages/DBFiles/details.php", headers=headers, data=dict(
    infosub='99176297'
))
read_html(single.text)
```

**Comment by lahoffm** [comment]
@ableonard  are you still working on this? If you don't have time to devote to this over next few weeks please let me know so I can open it up for others.

**Comment by ableonard** [comment]
@lahoffm fair question. This past month has been pretty busy for me, but I've got some of it parsing. I can clean up my fork and PR it back here this weekend. If there's someone who's interested in picking it up, they may be able to use it as a starting point.

**Comment by lahoffm** [comment]
A PR would be great, then someone can pick up where you left off.

**Comment by lahoffm** [comment]
@ableonard did great work and he has opened up this scraper for ANYONE to finish. Please post if you're taking it.

Current code is in https://github.com/lahoffm/aclu-bail-reform/tree/master/src/webscraper/gwinnett

Some things to work on:

- [ ] Middle name is not being extracted separately (just part of the first name value right now).
- [ ] The dates are not being output in the Postgres format, although I suspect the format can be parsed just fine for import.
- [ ] The default Gwinnett search results can produce more than one page of results. The scraper does not currently support fetching the additional results (via a "Load More Results" button).
- [ ] There's no support for searching released inmates. This is more of an additional feature, but it's the way to get information on how long an inmate is held.
- [ ] The date portion of the file name currently requires using the date util during invocation of the scraper. I couldn't decide if invoking the scraper should always produce the CSV-formatted file or if we should leverage the built-in support for multiple formats in Scrapy. This doesn't necessarily needing fixing, but it's worth thinking about.

**Comment by lahoffm** [comment]
- [ ] We also want ability to specify a date on command line and get all bookings on that date. See [Dekalb's readme](https://github.com/lahoffm/aclu-bail-reform/tree/master/src/webscraper/dekalb) something very similar to the "Custom date". The Gwinnett website lets you specify this through a form on the left side, so you can find a way to simulate that, along with search for both current and released inmates. Be sure to get ALL bookings on that date not just the first 20 (see the "Load more results" on the bottom?)
